import Header from "@/components/layout/Header";

import AdminAside from "@/components/admin/AdminAside";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
    title: "Gétime",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <section className="relative flex min-h-screen flex-1">
            <AdminAside />
            <div className="flex flex-1 flex-col overflow-hidden">
                <Header />
                <main className="flex flex-1 overflow-auto">{children}</main>
            </div>
            <Analytics />
        </section>
    );
}
