import Header from "@/components/layout/Header";

import AdminAside from "@/components/admin/AdminAside";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <section className="relative flex min-h-svh flex-1 flex-col">
            <AdminAside />
            <div className="xl:pl-72">
                <Header />
                <main>{children}</main>
            </div>
        </section>
    );
}
